name = "BTrDB"
uuid = "80a4795a-bd22-11e9-2da3-91d46100624a"
authors = ["looselycoupled <allen.leis@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
